import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

<ul className="flex justify-end space-x-8 p-4 bg-blue-500 text-black-500 max-w-7xl mx-auto p-4 sm:p-6 md:p-8">
            <li >
            <Link href="/home ">Home</Link>
            </li>
            <li >
            <Link href="/about"> About</Link>
            </li>
            <li >
            <Link href="/country">Country</Link>
            </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
